[tool.poetry]
name = "agent-config-backend"
version = "0.1.0"
description = "Backend for Eliza agent configuration"
authors = ["Devin <devin@devin.ai>"]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.104.1"
uvicorn = "^0.24.0"
pydantic = "^2.5.2"
python-dotenv = "^1.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
